#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <path_to_video_files>"
    exit 1
fi

referencedir="$1"
mkdir -p Retimed

for subtoretime in ./*.{ass,srt}; do
    [ -e "$subtoretime" ] || continue

    base_name="${subtoretime##*/}"
    base_name_no_ext="${base_name%.*}"

    referencevideo_mkv="$referencedir/$base_name_no_ext.mkv"
    referencevideo_mp4="$referencedir/$base_name_no_ext.mp4"

    if [ -f "$referencevideo_mkv" ]; then
        referencevideo="$referencevideo_mkv"
    elif [ -f "$referencevideo_mp4" ]; then
        referencevideo="$referencevideo_mp4"
    else
        echo "Warning: No matching reference video found for '$base_name'. Skipping..."
        continue
    fi

    retimed_sub="Retimed/${base_name_no_ext}_retimed.${subtoretime##*.}"
    ffsubsync "$referencevideo" -i "$subtoretime" -o "$retimed_sub"
    echo "Retimed '$subtoretime' using '$referencevideo' -> '$retimed_sub'"
done
